name: iOS Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List Schemes
      run: |
        xcodebuild -list -project "Frame Grabber.xcodeproj"

    - name: Build iOS app
      run: |
        xcodebuild -project "Frame Grabber.xcodeproj" -scheme FrameGrabber -sdk iphoneos -configuration Release
